create table if not exists goals(
    id bigint primary key generated by default as identity,
    user_id uuid default auth.uid() references auth.users(id) not null,
    task_id bigint not null,
    seconds_threshold bigint not null,
    goal_under_threshold boolean not null,
    completed boolean not null
);

alter table goals enable row level security;

create policy "Users can view their own goals."
on goals for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Users can create their own goals."
on goals for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Users can update their own goals."
on goals for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Users can delete their own goals."
on goals for delete
to authenticated
using ((select auth.uid()) = user_id);